ペットショップアプリ課題2
YaKumagai/pet_shop pull request #2
Opened 2021-02-24 08:10 UTC by YaKumagai

### 期待していた動作 や 質問内容
```
$sql = 'SELECT * FROM animals WHERE description LIKE "%大%"';
```
曖昧検索されます。
```
$keyword = '%大%';
$sql = 'SELECT * FROM animals WHERE description LIKE :keyword';
```
こちらでは、曖昧検索されません。

原因が分かりません。よろしくお願いします。

### カリキュラムURL や 本のページ番号
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise_org/02_pet_shop/02.md

### エラーメッセージ
なし

###  ソースコード or ソースコードのスクリーンショット

### 直前に行ったコマンド・操作

### 調べたこと・参考にしたURL

https://w.atwiki.jp/nicepaper/pages/230.html
```
$keyword = $_POST["keyword"];
$keyword = '%'.$keyword.'%';// %ではさむところがポイント
SELECT * FROM information WHERE comment LIKE :keyword;
```
$keyword = $_GET["keyword"];
  
SELECT * FROM [テーブル名] WHERE [カラム名] LIKE :keyword;
$keyword = '%'.$keyword.'%';// %ではさむ

### 使用PC : 該当するものだけ残して他2つは削除してください

- MacBook

### メーカーとモデル名(Windowsの方のみ/Macの方はこの項目削除してください)

2021-02-24 08:20 UTC, kazu-taka requested changes
@YaKumagai 
何点かコメントしたので確認お願いします🙏

2021-02-24 08:20 UTC, kazu-taka commented on index.php
> +</html>
@YaKumagai 
ここ以降にあるPHPのコードは、htmlの前に記述する必要があるので、PHPのコードをファイルの上部に書くようにお願いします🙏

2021-02-24 08:20 UTC, kazu-taka commented on index.php
> +    $keyword = '"%' . $keyword . '%"';
@YaKumagai 
`$keyword = '"%' . $keyword . '%"';`の部分ですが、`"`があるせいで、SQLがうまく動いていない可能性があります！
`$keyword = '%' . $keyword . '%'`に修正して動作確認をお願いします🙏
また`:keyword`とパラメーターにしていますが、bindParamで:keywordを$keywordで置き換える必要があるので、修正お願いします🙏
🙏

2021-02-25 00:12 UTC, noopy0415 commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
※変数を直接記述するには、シングルクォーテーションでは変数が展開されないので、ダブルクォーテーションに変更したり、LIKE検索する値はシングルクォーテーションを追加するなどが必要です😅

でも、この部分は後から置き換えるための目印としてプレースホルダー(:が付く)にしてください👍
変数や検索値などを直接記述する方法は、使いまわししづらくなるので、プレースホルダーをバインドパラメータで置き換える方法を使いましょう😊

2021-02-25 00:19 UTC, YaKumagai commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
そうなんです。どのようにしたら良いか分かりませんでした。💦

2021-02-25 00:27 UTC, YaKumagai commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
`$keyword` をどのように `:keyword` にわたすことが出来るか分かりません。
ここで、悩んでいます。🙏

2021-02-25 00:32 UTC, noopy0415 commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
ステートメントを作った後に
`$stmt->bindParam(':プレースホルダー', $変数, PDO::PARAM_STR);`
でバインド出来ます👍

カリキュラムだとこの辺になります✨
https://github.com/elites-team/2months_course/blob/master/doc/06_php/study02/02_pdo/01.md#222-%E3%83%97%E3%83%AA%E3%83%9A%E3%82%A2%E3%83%89%E3%82%B9%E3%83%86%E3%83%BC%E3%83%88%E3%83%A1%E3%83%B3%E3%83%88%E3%81%A8%E3%83%97%E3%83%AC%E3%83%BC%E3%82%B9%E3%83%9B%E3%83%AB%E3%83%80%E3%81%AB%E3%82%88%E3%82%8B%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E5%87%A6%E7%90%86

2021-02-25 00:35 UTC, noopy0415 commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
今回はLIKE検索なのでバインド前に一手間必要になります😇
キーワードの完全一致の場合はキーワードだけですが、曖昧検索なので。。。

2021-02-25 00:53 UTC, YaKumagai commented on index.php
> +        'FROM animals WHERE description LIKE $keyword ORDER BY id ASC';
ありがとうございます。
カリキュラムの質問にも書きましたが、`name="<?= h("keyword") ?>"` 12行目

sqlの、キーワード検索ボックスの動作について、
name="<?= h("keyword") ?>">
<?php ?> の省略が、 <?= ?> と思っていました。
それぞれ、動作が違うようです。

調べてみましたら、
https://qiita.com/maimai-swap/items/01685c839534146a82f8

name="<?= h("keyword") ?>"> の使い方正しいでしょうか？

カリキュラムの質問
https://elites-team.kibe.la/notes/5842#comment_reply_4525


今回、丸覚えのため、理解し切れていません💦

ありがとうございました😊

2021-02-25 08:25 UTC, noopy0415 reviewed
HTMLの中にPHPの埋め込みを行っているので、PHPのコードはHTMLの上に記述した方が良いです。
(HTMLが先だと変数が定義されていないエラーが発生する場合があります)

```php
<?php
// PHPのコード
?>
<!-- HTMLのコード -->
```

2021-02-25 08:25 UTC, noopy0415 commented on index.php
> +        <input name="<?= h("keyword") ?>" placeholder="キーワードを入力下さい" size="24" type="text">
name属性にはh()は必要無いです😊

2021-02-25 08:25 UTC, noopy0415 commented on index.php
> +$keyword = h($_GET["keyword"]);
変数に代入する場合もh()関数は必要無いです😊

2021-02-25 08:25 UTC, noopy0415 commented on index.php
> +    echo '<br>' . $animal['type'] . 'の' .
`<br>`タグは文章の最後につけるようにするとスッキリします😊

2021-02-25 08:52 UTC, YaKumagai commented on index.php
> +$keyword = h($_GET["keyword"]);
h()関数は、どこで使うと好ましいですか？

2021-02-25 08:53 UTC, YaKumagai commented on index.php
> +    echo '<br>' . $animal['type'] . 'の' .
`<br>タグは、どこに入れたらよろしいですか？
思うような動作はしませんでしたので、この様な形になりました。

2021-02-25 09:19 UTC, noopy0415 commented on index.php
> +    echo '<br>' . $animal['type'] . 'の' .
表示をあわせる為に使っているんですね？
`<br>`タグは改行する為のタグなので、隙間を空ける為には使用しない方が良いです😅

今回はキーワードの行と表示する1件目の表示との間に隙間を入れたかったので`<br>`を使っていましたが、まとまった情報の場合は`<div>`タグや`<p>`タグを使うと調整しやすくなります👍

問題の画像は`<p>`タグを使っているので、自動で上下にmarginが入って隙間ができています👍

2021-02-25 09:24 UTC, noopy0415 reviewed
前の部分のコメントと一緒に確認お願いします😊

2021-02-25 09:24 UTC, noopy0415 commented on index.php
>          $animal['classifcation'] . 'ちゃん' . '<br>' .
foreachのところは表示する部分なので、HTMLの中に埋め込んで記述した方が良いです😅

`<body>`~`</body>`内に埋め込んでください😊

2021-02-25 09:24 UTC, noopy0415 commented on index.php
> +        <?php echo '「' . h($_GET["keyword"]) . '」で、曖昧検索しました'; ?>
このままでも良いですが、`<?php echo`はショートタグの`<?=`に置き換えてもOKです👍
```diff
- <?php echo '「' . h($_GET["keyword"]) . '」で、曖昧検索しました'; ?>
+ <?= '「' . h($_GET["keyword"]) . '」で、曖昧検索しました'; ?>
```

2021-02-25 10:54 UTC, kazu-taka commented
@YaKumagai 
問題ないと思います😊
コードもとても綺麗で見やすいです✨
マージしてOKです！！
![LGTM](https://image.lgtmoon.dev/117665)

2021-02-25 11:36 UTC, merged